# Exported from:        http://esenkus-Precision-5480:5516/
# Release version:      24.1.0
# Date created:         Thu May 29 15:23:10 EEST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Version_stuff
spec:
- name: HTTP Endpoint for Deploy
  type: events.PostWebhookEndpoint
  path: path-8a23edbe-51f7-4806-990c-fa1c95cb9a94
  authentication:
    type: events.NoAuthentication
- name: Live Deployments config for Deploy
  type: deploy.DeploymentConfig
  application: Applications/.*
  environment: Environments/.*
- name: API Server Deploy
  type: digitalai.DeployServer
  url: http://localhost:4516
  username: admin
  password: !value "digitalai_DeployServer_API_Server_Deploy_password"
- name: Flux Git Repo
  type: fluxcd.GitConfig
  username: esenkus
  url: https://github.com/esenkus/flux-test
  fluxcdGitRepositoryAuthenticationMethod: Basic Auth
  password: !value "fluxcd_GitConfig_Flux_Git_Repo_password"
  committerUsername: esenkus
  branch: main
  path: clusters/my-cluster
- name: Webhook Source for Deploy
  type: deploy.StatusWebhookEventSource
  eventSource: HTTP Endpoint for Deploy
  sourceServer: API Server Deploy
  liveDeploymentConfigs:
  - Live Deployments config for Deploy
